11 вариант template
Wloveyou/ProgrammingLanguages-3-1 pull request #2
Opened 2023-11-20 15:43 UTC by Wloveyou

![photo_5395421875712153283_y](https://github.com/Wloveyou/ProgrammingLanguages-3-1/assets/113116179/4f9b8f7a-1966-433a-a293-a3ad356276df)

2023-11-23 11:43 UTC, MarinaPaley requested changes
![image](https://github.com/Wloveyou/ProgrammingLanguages-3-1/assets/26978698/abf320d6-31e2-479c-81c6-564582cecb41)
Зачем все это?

2023-11-23 11:43 UTC, MarinaPaley commented on 4.1.cpp
> +#include <math.h>
Почему так?

2023-11-23 11:43 UTC, MarinaPaley commented on 4.1.cpp
> +        Point(const T x = 0, const T y = 0);
Если T тип данных ... vector? тоже значение 0?

2023-11-23 11:43 UTC, MarinaPaley commented on 4.1.cpp
> +    return x == y;
А кто гарантирует, что тип имеет оператор сравнения?

2023-11-24 15:10 UTC, Wloveyou commented on 4.1.cpp
> +#include <math.h>
Забыл убрать

2023-11-24 15:10 UTC, Wloveyou commented on 4.1.cpp
> +        Point(const T x = 0, const T y = 0);
забыл убрать 0

2023-11-24 15:20 UTC, Wloveyou commented on 4.1.cpp
> +        Point(const T x = 0, const T y = 0);
Забыл убрать 0

2023-11-24 15:20 UTC, Wloveyou commented on 4.1.cpp
> +    return x == y;
Мы предполагаем что будет использоваться стандартные типы которые имеют оператор сравнения ( int, double) или же реализованные нами для которых будем реализовывать оператор сравнения

2023-11-27 16:23 UTC, MarinaPaley commented on 4.1.cpp
> +    return x == y;
ээээ... Вы готовы использовать `concept`?

2024-03-08 11:58 UTC, closed without merging